steps:

- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
  args: ['-f','docker-compose.cloudbuild.yaml','up','-d']

- id: "Rodando docker ps"
  name: 'gcr.io/cloud-builder/docker'
  args: ['ps']

- id: "Rodando composer"
  name: 'grc.io/cloud-builders/docker'
  args: ['exec','-t','app','composer','install']

- id: "Copiando .env"
  name: 'grc.io/cloud-builders/docker'
  args: ['exec','-t','app','cp','.env.exemple','.env']

- id: "Rodando key:generate"
  name: 'grc.io/cloud-builders/docker'
  args: ['exec','-t','app','/var/www/artisan','key:generate']

- id: "Rodando migrations"
  name: 'grc.io/cloud-builders/docker'
  args: ['exec','-t','app','/var/www/artisan','migrate']

- id: "Rodando phpunit"
  name: 'grc.io/cloud-builders/docker'
  args: ['exec','-t','app','php','/var/www/vendor/bin/phpunit','-c','/var/www/phpunit.xml']





  
